[package]
name = "qrstore"
version = "0.1.0"
authors = ["Arvid Böttiger <arvid@exensor.com>"]
edition = "2018"
#build = "build.rs"

#[lib]
#name = "qrstore"
#crate-type = ["rlib", "dylib"] # could be `staticlib` as well
#build = "build.rs"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[[bin]]
name = "rest"
path = "src/bin/rest.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel =         { version = "*", default-features = false, features = ["sqlite", "chrono"] }
# Needed for sqlite.
libsqlite3-sys = { version = "*", features = ["bundled"] }

dotenv = "0.15"
rand  = "0.7"
chrono = "0.4"
clap = "2.33"
qrcode = "0.11"
image = "0.22"
bardecoder = "0.2"
actix-web = "2.0"
actix-rt = "1.0.0"
rusoto_core = "0.42"
rusoto_dynamodb = "0.42"
